### ISSUE TITLE
Toolbar states don't work on initial content

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-article#1]
Since the range toolbar state updater relies on the `plugin` event to update its state, it doesn't work with saved or static content (ie: highlight bold text in saved content, bold tool does not show as active).

Two possible solutions:

- Make the plugin event fire for all plugin outputs present in first render
- Make toolbar state update on selection, not `plugin`

**Comment by bedeoverend** [comment]
That's odd - I'm pretty sure the `plugin` event should fire when you highlight the text, as at that point the `bold` state changes it's `applied` prop to `true`. I'll dig some more into this, but could mean it's an issue in RichText

**Comment by madeleineostoja** [comment]
I'll update deps and see if that fixes it, just realised I may have still been on RichText 0.3.x

**Comment by madeleineostoja** [comment]
Only doesn't work on first range highlight.

Repro 1:
- In static content demo, highlight heading (heading tool not active)

Repro 2: 
- In static content demo, highlight some unformatted text
- Now highlight heading (heading tool active)
