### ISSUE TITLE
Toggling link prompt causes toolbar to lose positioning in Edge

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-article#10]
Clicking the link tool in the range toolbar in Edge opens the link prompt, but causes the whole range toolbar to lose its positioning and jump to the top left corner of the screen.

**Comment by madeleineostoja** [comment]
Yeah I'll add breaking back to this one - it's a super common use-case, and it's pretty jarring. Technically doesn't break the ability to use the article, but does make it a pretty unpleasant experience for Edge users.

**Comment by bedeoverend** [comment]
Fair enough, I haven't tried it out myself, but it sounds pretty damn awful.

**Comment by bedeoverend** [comment]
Ok so richtext 0.4.3 should fix this. @seaneking could you double check?

**Comment by bedeoverend** [comment]
Though think it shows up a nastier bug of hitting enter in link removing the selected text.

**Comment by bedeoverend** [comment]
Actually the bug of hitting enter and removing the selectext text is global, not just on Edge, will make a separate bug

**Comment by madeleineostoja** [comment]
Yep fixed 👍
