### ISSUE TITLE
Image toolbar not positioned correctly on Edge

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-article#11]
The image toolbar is very inconsistently positioned on Edge, and never positioned in the right spot. It usually ends up at the bottom left corner of the image, or above the whole article with the rest of the text highlighted as well.

**Comment by bedeoverend** [comment]
I think this was fixed in v0.4.3 of richtext - @seaneking could you confirm?

**Comment by madeleineostoja** [comment]
Yep fixed 👍
