### ISSUE TITLE
Toolbars shouldn't be sticky positioned to viewport

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-article#12]
Wrong behavior for a text formatting toolbar, if it's still visible after the thing it's editing is out of view. Assume this is just config we can disable on Popper?

Screencap of incorrect behavior:

![toolbar](https://cloud.githubusercontent.com/assets/6374876/26591266/69ba7cc4-455d-11e7-8066-1462349086d1.gif)

**Comment by madeleineostoja** [comment]
Hmm looks like this isn't just simple config. We'd want the basic keep-in-viewport behavior, but only on initial open, not updated on scroll

**Comment by bedeoverend** [comment]
This is an issue I flagged with Popper, but turns out I was just doing implementation wrong, I'll see if that's happening again here, otherwise will try raise something with popper.

**Comment by bedeoverend** [comment]
Was just incorrect boundary config - using `viewport` when should have really been using `scrollParent`

**Comment by madeleineostoja** [comment]
Does it still respect the viewport if you highlight a range at the top of the viewport, for example?

**Comment by bedeoverend** [comment]
Yup - so it still does it's best to stay in the viewport, but doesn't break away from the element

**Comment by madeleineostoja** [comment]
:+1: We should probably bail on viewport resize now though, since that now breaks positioning
