### ISSUE TITLE
JS Module import

### ISSUE THREAD

**Issue by musicsmithnz** [SimplaElements/simpla-article#18]
are there plans to make this available to use as a JS Module import  that works with Polymer 3 ?   Would you need help with that ?

**Comment by bedeoverend** [comment]
@musicsmithnz certainly are plans, though we haven't made much headway yet. Would love to get your input / help though! We've got an issue over at https://github.com/simplajs/simpla/issues/79 tracking this.

Given that main issue, I'll close this, but feel free to comment if there's something specific to article you'd like to raise
