### ISSUE TITLE
Opening link prompt causes range toolbar to close in Firefox

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-article#9]
Tapping the link icon in the toolbar to open the link prompt causes the whole range toolbar to close in Firefox

**Comment by bedeoverend** [comment]
Took a look into this one, seems that [Firefox doesn't focus on buttons](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus) which means it doesn't have a `relatedTarget` on the `blur` event so [this check](https://github.com/SimplaElements/simpla-article/blob/master/src/simpla-article-toolbar.html#L454) doesn't work, and it thinks the context should go to null. Tried the alternative code of:

```js
this.async(() => {
  if (document.activeElement !== this && !this.contains(document.activeElement)) {
    this.context = null;
  }
}, 1);
```

but that caused regressions where clicking bold / italic etc. would close the toolbar in Chrome etc. Not sure what to do with this one, but just a heads up on what I could find.

**Comment by bedeoverend** [comment]
Alternatively, as a temporary hack, could use [`explicitOriginalTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/explicitOriginalTarget) as well as `relatedTarget`. It gets the button, but it's specific to Firefox and is non-standard, so who knows when it'll get stripped out.

**Comment by madeleineostoja** [comment]
You can just give the buttons a tabindex to make them focusable

**Comment by bedeoverend** [comment]
Tried that, no dice - checkout that link to MDN, shows table of where it apparently works, and where not.

**Comment by madeleineostoja** [comment]
God damnit Firefox, why oh why would you make buttons, of all things, completely unfocusable.

Okay, easy patch would be to make all the buttons anchors, assuming that they're allowed to have focus under FF.

I'll have a okay today.

**Comment by madeleineostoja** [comment]
Bah, only on OSX too, that said apparently iOS doesn't support it either (though latest data in that article is iOS 7.x sooo...)

For now I'll just make them anchors, which is gross and unsemantic... stupid browser vendors.
